package com.arittek.befiler_services.util;

public enum Constants {

	NEW_USER,
	ACTIVE,
	DE_ACTIVE,
	APPROVE,
	DIS_APPROVE,
	FORM_SUBMITED_FBR,
	FORM_SUBMITED_BHARDOTAX,
	PAYMENT_IN_PROCESS,
	ASSIGN_LAWYER,
	PAYMENT_ISSUE,
	PAYMENT_VERIFIED,
	FROM_RE_SUBMITED_BHARDOTAX,
	DISABLE,
	FORM_CORRECTION,
	EMAIL_SENT,
	EMAIL_SENDING_FAILD,
	ENCRIPT_ID
}
